export const exploreDataObj = {
  grades: [
      "6th grade",
      "7th grade",
      "8th grade",
      "9th grade",
      "10th grade",
      "11th grade",
      "12th grade",
      "Medical Studies",
      "Engineering Studies",
      "Business Studies",
      "Science",
      "Computer Science and IT",
      "Social Science",
      "Humanities",
      "Education",
      "Law",
      "Creative Arts",
      "Health Sciences",
      "Environmental Studies",
      "Agricultural Sciences",
      "Media and Communication",
      "Hospitality and Tourism",
      "Design",
      "Others"
  ],
  subject: [
    "accounting",
      "agricultural science",
      "anthropology",
      "archaeology",
      "architecture",
      "art history",
      "astronomy",
      "biochemistry",
      "biology",
      "biomedical science",
      "biotechnology",
      "botany",
      "business administration",
      "chemical engineering",
      "chemistry",
      "civics",
      "civil engineering",
      "classics",
      "communication studies",
      "computer science",
      "criminology",
      "dentistry",
      "defense studies",
      "earth science/geology",
      "economics",
      "education",
      "electrical engineering",
      "environmental science",
      "film studies",
      "finance",
      "fine arts",
      "food science",
      "forensic science",
      "genetics",
      "geography",
      "graphic design",
      "health sciences",
      "history",
      "home science",
      "human resources",
      "information technology",
      "journalism",
      "languages and linguistics",
      "law",
      "literature",
      "management",
      "marketing",
      "mathematics",
      "mechanical engineering",
      "media studies",
      "medicine",
      "microbiology",
      "music",
      "nursing",
      "nutrition",
      "pharmacy",
      "philosophy",
      "physics",
      "political science",
      "psychology",
      "public administration",
      "religious studies",
      "self development",
      "science",
      "social science",
      "sociology",
      "software engineering",
      "sports science",
      "statistics",
      "theater arts",
      "tourism and hospitality",
      "urban planning",
      "veterinary science",
      "water security",
      "web design and development",
      "women's studies",
      "zoology"
  ],
  category: [
      "ACADEMICS",
      "NON ACADEMICS",
      "RESEARCH",
      "UPSC",
      "JEE",
      "NEET"
  ],
  publisher: [
      "NCERT",
      "SCERT",
      "GCERT",
      "DSERT",
      "MSB",
      // "VK Global",
      // "New Age",
      // "Jeevandeep Edumedia",
      // "UNIQUE"
  ],
}